version: "3.2"

services:
  login:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      JAEGER_HOST_PORT: "jaeger:6832"
    volumes:
      - ./test/key.pem:/secrets/key/private.pem

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
    - "5775:5775"
    - "6831:6831"
    - "6832:6832"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
    - 9090:9090
